# Stage 1: Build the Next.js application
FROM node:18-alpine AS builder

WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./

# Copy the rest of the application code
COPY . .

# Install only production dependencies
RUN printf Y | pnpm install 

EXPOSE 6006

# Start the Next.js application
CMD ["pnpm", "run", "storybook"]
