export enum COLORS {
  BG_LIGHT_ORANGE_COLOR = "#FFF7E9",
  BG_LIGHT_GREY_COLOR = "#F7F7F7",
  BG_DARK_GREEN_COLOR = "#005F56",
  PRIMARY_COLOR = "#FF6600",
  SECONDARY_TEXT_COLOR = "#666",
  BORDER_COLOR = "#E0E0E0",
  BLACK_COLOR = "black",
  WHITE_COLOR = "white",
}
